services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - 'traefik.http.routers.app.rule=Host(`openwebui.${CUSTOMDOMAIN}`)'
        - 'traefik.http.routers.app.entrypoints=web'
        - 'traefik.http.services.app.loadbalancer.server.port=8080'
        - 'traefik.http.routers.app-https.rule=Host(`openwebui.${CUSTOMDOMAIN}`)'
        - 'traefik.http.routers.app-https.entrypoints=websecure'
        - 'traefik.http.services.app-https.loadbalancer.server.port=8080'
        - 'traefik.http.routers.app-https.tls=true'
        - 'traefik.http.routers.app-https.tls.certresolver=cloudflare'
        - 'traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https'
        - 'traefik.http.routers.app.middlewares=app-https-redirect'

volumes:
  ollama: {}
  open-webui: {}