services:
  ollama:
    container_name: ollama
    volumes:
      - "${OLLAMA_FOLDER_PATH}:/root/.ollama"
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG}
    networks:
      - shared_network

  open-webui:
    container_name: open-webui
    # build:
    #   context: .
    #   args:
    #     OLLAMA_BASE_URL: '/ollama'
    #   dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG}
    volumes:
      - open-webui:/app/backend/data
    security_opt:
      - no-new-privileges
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - CUSTOMDOMAIN=${CUSTOMDOMAIN} #unnecessary?
    env_file: .env 
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.openwebui.entrypoints=web'
      - 'traefik.http.routers.openwebui.rule=Host(`openwebui.${CUSTOMDOMAIN}`)'
      - 'traefik.http.routers.openwebui-secure.entrypoints=websecure'
      - 'traefik.http.routers.openwebui-secure.rule=Host(`openwebui.${CUSTOMDOMAIN}`)'
      - 'traefik.http.routers.openwebui-secure.tls=true'
      - 'traefik.http.routers.openwebui-secure.tls.certresolver=cloudflare'
      - 'traefik.http.services.openwebui.loadbalancer.server.port=8080'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.openwebui.middlewares=redirect-to-https'

volumes:
  ollama: {}
  open-webui: {}

networks:
  shared_network:
    external: true