# Variables
APP_NAME := openwebui

# Default target
all: help

# Include common definitions and targets
include ../common.mk

# Help message
help: common-help
	@echo "  help           - Show this help message"

.PHONY: all help
