version: '3.8'

services:
  shellngn-pro:
    image: shellngn/pro:latest
    ports:
      - "8999:8080"
    environment:
      - HOST=0.0.0.0
    volumes:
      - shellngn-data:/home/node/server/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  shellngn-data:
    driver: local

