# Variables
APP_NAME := shellngn

# Include common definitions and targets
include ../common.mk

# Default target
all: help

# Help message
help:
	@echo "Available commands:"
	@$(info $(COMMON_HELP))
	@echo "  help           - Show this help message"

.PHONY: all help
