services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    labels:
      - 'traefik.enable=true'
      # HTTP Router
      - 'traefik.http.routers.n8n.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.n8n.entrypoints=web'
      - 'traefik.http.routers.n8n.middlewares=redirect-to-https'
      # HTTPS Router
      - 'traefik.http.routers.n8n-secure.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.n8n-secure.entrypoints=websecure'
      - 'traefik.http.routers.n8n-secure.tls=true'
      - 'traefik.http.routers.n8n-secure.tls.certresolver=cloudflare'
      # Service
      - 'traefik.http.services.n8n.loadbalancer.server.port=${N8N_PORT}'
      # Middleware for HTTPS redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
    environment:
      - N8N_HOST=${DOMAIN_PREFIX}.${DOMAIN}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=https://${DOMAIN_PREFIX}.${DOMAIN}/
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
          pids: "${PIDS_LIMIT}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
volumes:
  n8n_data:

networks:
  shared_network:
    external: true
