---
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    labels:
      - 'traefik.enable=true'
      # HTTP Router
      - 'traefik.http.routers.n8n.rule=Host(`${DOMAIN_PREFIX}.${CUSTOMDOMAIN}`)'
      - 'traefik.http.routers.n8n.entrypoints=web'
      - 'traefik.http.routers.n8n.middlewares=redirect-to-https'
      # HTTPS Router
      - 'traefik.http.routers.n8n-secure.rule=Host(`${DOMAIN_PREFIX}.${CUSTOMDOMAIN}`)'
      - 'traefik.http.routers.n8n-secure.entrypoints=websecure'
      - 'traefik.http.routers.n8n-secure.tls=true'
      - 'traefik.http.routers.n8n-secure.tls.certresolver=cloudflare'
      # Service
      - 'traefik.http.services.n8n.loadbalancer.server.port=5678'
      # Middleware for HTTPS redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
    environment:
      - N8N_HOST=${DOMAIN_PREFIX}.${CUSTOMDOMAIN}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=https://${DOMAIN_PREFIX}.${CUSTOMDOMAIN}/
      - GENERIC_TIMEZONE=${TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - shared_network
    pids_limit: 100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_network:
    external: true

volumes:
  n8n_data:



