---
services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n-http.entrypoints=web
      - 'traefik.http.routers.n8n-http.rule=Host(`n8n.${CUSTOMDOMAIN}`)'
      - traefik.http.routers.n8n-https.entrypoints=websecure 
      - 'traefik.http.routers.n8n-https.rule=Host(`n8n.${CUSTOMDOMAIN}`)'
      - traefik.http.routers.n8n-https.tls=true
      - traefik.http.routers.n8n-https.tls.certresolver=cloudflare
      # - traefik.http.middlewares.n8n-https.headers.SSLRedirect=true
      # - traefik.http.middlewares.n8n-https.headers.browserXSSFilter=true
      # - traefik.http.middlewares.n8n-https.headers.contentTypeNosniff=true
      # - traefik.http.middlewares.n8n-https.headers.forceSTSHeader=true
      # - traefik.http.middlewares.n8n-https.headers.STSIncludeSubdomains=true

      # - traefik.http.middlewares.n8n-https.headers.STSSeconds=315360000
      # - 'traefik.http.middlewares.n8n-https.headers.SSLHost=${CUSTOMDOMAIN}'
      # - traefik.http.middlewares.n8n-https.headers.STSPreload=true
    environment:
      - N8N_HOST=${CUSTOMDOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=http://${CUSTOMDOMAIN}/
      - GENERIC_TIMEZONE=Europe/Istanbul
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  n8n_data:



