services:
  browser-use:
    build: .
    container_name: browser-use
    restart: unless-stopped
    networks:
      - shared_network
    ports:
      - "5901:5901"  # VNC
      - "6080:6080"  # noVNC
      - "7788:7788"  # API
      - "9222:9222"  # Chrome DevTools
    environment:
      - DISPLAY=:99
      - RESOLUTION=1920x1080x24
    command: >
      bash -c "
        Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset &
        x11vnc -display :99 -N -forever -shared &
        /usr/share/novnc/utils/launch.sh --vnc localhost:5901 --listen 6080 &
        playwright install chromium &&
        python3 -m browser_use"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7788/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_network:
    external: true