services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"  # DHCP kullanılıyorsa
    environment:
      TZ: 'Europe/Istanbul'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.rule=Host(`pihole.${HOMEDOMAIN}`)"
        - "traefik.http.routers.pihole.entrypoints=web"  # Port 80'den gelen trafik
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - pihole_network
      - shared_network
networks:
  pihole_network:
    driver: overlay
  shared_network:
    external: true