version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "7001:80/tcp"
      - "7002:443/tcp"
    environment:
      TZ: 'Europe/Istanbul'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    depends_on:
      - traefik
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.rule=Host(`pihole.${HOMEDOMAIN}`)"
        - "traefik.http.routers.pihole.entrypoints=web"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - pihole_network
      - shared_network

networks:
  pihole_network:
    driver: overlay
  shared_network:
    external: true
