services:
  traefik:
    image: "traefik:v3.3.4"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:80"  # Port 80'e gelen HTTP trafiği
      - "--entrypoints.websecure.address=:443" # Port 443'e gelen HTTPS trafiği
      - "--entrypoints.traefik.address=:8080"  # Dashboard için ayrı port
      - "--ping"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/traefik.toml"
      - "./traefik/acme.json:/acme.json"
    deploy:
      mode: global
    networks:
      - shared_network

networks:
  shared_network:
    external: true
