services:
  traefik:
    image: "traefik:v3.3.4"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.traefik.address=:8080"
      - "--ping"
    ports:
      - target: 8081
        published: 8081
        mode: host
      - target: 8443
        published: 8443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: global
    networks:
      - shared_network

networks:
  shared_network:
    external: true
