services:
  traefik:
    image: "traefik:v3.3.4"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    environment:
      - CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      - CF_API_EMAIL: ${CLOUDFLARE_API_EMAIL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./data/log:/var/log"
      - "./data/certs/:/var/traefik/certs/:rw"
    deploy:
      mode: global
    networks:
      - shared_network

networks:
  shared_network:
    external: true
