---
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
 level: DEBUG
api:
  insecure: true
  dashboard: true
accessLog:
  filePath: "/var/log/access.log"
  format: "json"
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  traefik:
    address: ":8080"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # <-- (Optional) Change this to true if you want to expose all services
    # Specify discovery network - This ensures correct name resolving and possible issues with containers, that are in multiple networks.
    # E.g. Database container in a separate network and a container in the frontend and database network.
    network: shared_network