services:
  hydra-migrate:
    container_name: ${HYDRA_MIGRATE_CONTAINER}
    image: oryd/hydra:${HYDRA_VERSION}
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&max_conns=${DB_MAX_CONNS}&max_idle_conns=${DB_MAX_IDLE_CONNS}
    networks:
      - shared_network
    pids_limit: 100
    depends_on:
      hydra_postgres:
        condition: service_healthy

  hydra_postgres:
    container_name: hydra-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - shared_network
    pids_limit: 100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  hydra:
    container_name: ${HYDRA_CONTAINER}
    image: oryd/hydra:${HYDRA_VERSION}
    command: serve -c /etc/config/hydra/config.yml all --dev
    ports:
      - "${HOST_PORT}:4444" # Public port
      - "${ADMIN_PORT}:4445" # Admin port
      # - "${TOKEN_PORT}:5555" # Port for hydra token user
    volumes:
      - type: bind
        source: ./hydra/config.yml
        target: /etc/config/hydra/config.yml
    pull_policy: missing
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&max_conns=${DB_MAX_CONNS}&max_idle_conns=${DB_MAX_IDLE_CONNS}
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - hydra_postgres
    networks:
      - shared_network
    pids_limit: 100
    labels:
      # Public API (4444)
      - 'traefik.enable=true'
      - 'traefik.http.routers.hydra-public.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-public.entrypoints=web'
      - 'traefik.http.routers.hydra-public-secure.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-public-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-public-secure.tls=true'
      - 'traefik.http.routers.hydra-public-secure.tls.certresolver=cloudflare'
      - 'traefik.http.services.hydra-public.loadbalancer.server.port=4444'

      # Admin API (4445)
      - 'traefik.http.routers.hydra-admin.rule=Host(`${DOMAIN_PREFIX}-admin.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-admin.entrypoints=web'
      - 'traefik.http.routers.hydra-admin-secure.rule=Host(`${DOMAIN_PREFIX}-admin.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-admin-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-admin-secure.tls=true'
      - 'traefik.http.routers.hydra-admin-secure.tls.certresolver=cloudflare'
      - 'traefik.http.services.hydra-admin.loadbalancer.server.port=4445'

      # Token API (5555)
      - 'traefik.http.routers.hydra-token.rule=Host(`${DOMAIN_PREFIX}-token.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-token.entrypoints=web'
      - 'traefik.http.routers.hydra-token-secure.rule=Host(`${DOMAIN_PREFIX}-token.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-token-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-token-secure.tls=true'
      - 'traefik.http.routers.hydra-token-secure.tls.certresolver=cloudflare'
      - 'traefik.http.services.hydra-token.loadbalancer.server.port=5555'

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4444/health/ready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

networks:
  shared_network:
    external: true