services:
  hydra-migrate:
    container_name: ${HYDRA_MIGRATE_CONTAINER}
    image: oryd/hydra:${HYDRA_VERSION}
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HYDRA_POSTGRES_HOST}:5432/${HYDRA_DATABASE}?sslmode=disable&max_conns=${DB_MAX_CONNS}&max_idle_conns=${DB_MAX_IDLE_CONNS}
    networks:
      - shared_network
    pids_limit: 100

  hydra:
    container_name: ${HYDRA_CONTAINER}
    image: oryd/hydra:${HYDRA_VERSION}
    command: serve -c /etc/config/hydra/config.yml all --dev
    ports:
      - "${HOST_PORT}:4444" # Public port
      - "${ADMIN_PORT}:4445" # Admin port
      # - "${TOKEN_PORT}:5555" # Port for hydra token user
    volumes:
      - type: bind
        source: ./hydra/config.yml
        target: /etc/config/hydra/config.yml
    pull_policy: missing
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HYDRA_POSTGRES_HOST}:5432/${HYDRA_DATABASE}?sslmode=disable&max_conns=${DB_MAX_CONNS}&max_idle_conns=${DB_MAX_IDLE_CONNS}
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - shared_network
    pids_limit: 100
    labels:
      - 'traefik.enable=true'
      # Public API (4444)
      - 'traefik.http.routers.hydra-public.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-public.entrypoints=web'
      - 'traefik.http.routers.hydra-public.service=hydra-public'
      - 'traefik.http.routers.hydra-public-secure.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-public-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-public-secure.tls=true'
      - 'traefik.http.routers.hydra-public-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.hydra-public-secure.service=hydra-public'
      - 'traefik.http.services.hydra-public.loadbalancer.server.port=4444'

      # Admin API (4445)
      - 'traefik.http.routers.hydra-admin.rule=Host(`${DOMAIN_PREFIX_ADMIN}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-admin.entrypoints=web'
      - 'traefik.http.routers.hydra-admin.service=hydra-admin'
      - 'traefik.http.routers.hydra-admin-secure.rule=Host(`${DOMAIN_PREFIX_ADMIN}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-admin-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-admin-secure.tls=true'
      - 'traefik.http.routers.hydra-admin-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.hydra-admin-secure.service=hydra-admin'
      - 'traefik.http.services.hydra-admin.loadbalancer.server.port=4445'

      # Token API (5555)
      - 'traefik.http.routers.hydra-token.rule=Host(`${DOMAIN_PREFIX_TOKEN}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-token.entrypoints=web'
      - 'traefik.http.routers.hydra-token.service=hydra-token'
      - 'traefik.http.routers.hydra-token-secure.rule=Host(`${DOMAIN_PREFIX_TOKEN}.${DOMAIN}`)'
      - 'traefik.http.routers.hydra-token-secure.entrypoints=websecure'
      - 'traefik.http.routers.hydra-token-secure.tls=true'
      - 'traefik.http.routers.hydra-token-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.hydra-token-secure.service=hydra-token'
      - 'traefik.http.services.hydra-token.loadbalancer.server.port=5555'

    healthcheck:
      test: >
        /bin/sh -c '
        wget --header="Origin: http://localhost" -qO- http://localhost:4444/health/ready || exit 1;
        wget --header="Origin: http://localhost" -qO- http://localhost:4445/health/ready || exit 1;
        '
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_network:
    external: true