services:
  pihole:
    image: pihole/pihole:latest
    ports:
      # - "53:53/tcp"
      # - "53:53/udp"
      - "67:67/udp"  # DHCP kullanılıyorsa
      - "7001:80/tcp"
      - "7002:443/tcp"
    environment:
      TZ: 'Europe/Istanbul'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - 'traefik.http.routers.app.rule=Host(`pihole.${CUSTOMDOMAIN}`)'
        - traefik.http.routers.app.entrypoints=web   #Port 80'den gelen trafik
        - traefik.http.services.app.loadbalancer.server.port=80
        - 'traefik.http.routers.app-https.rule=Host(`pihole.${CUSTOMDOMAIN}`)'
        - traefik.http.routers.app-https.entrypoints=websecure  # Port 80'den gelen trafik
        - traefik.http.services.app-https.loadbalancer.server.port=80
        - traefik.http.routers.app-https.tls=true
        - traefik.http.routers.app-https.tls.certresolver=cloudflare
    networks:
      - pihole_network
      - shared_network
networks:
  pihole_network:
    driver: overlay
  shared_network:
    external: true