# Variables
APP_NAME := anything-llm

# Default target
all: help

# Include common definitions and targets
# Note: common.mk already includes setup-interactive.mk, so we don't need to include it again
include ../common.mk

# Help message
help: common-help
	@echo "  help           - Show this help message"

.PHONY: all help
