services:
  minio:
    container_name: minio
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: server /data --console-address ":9001"
    volumes:
      - './minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
      - MINIO_BROWSER_REDIRECT_URL=https://${MINIO_CONSOLE_DOMAIN_PREFIX}.${DOMAIN}
    labels:
      - 'traefik.enable=true'
      # HTTP Router - API (9000)
      - 'traefik.http.routers.minio.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.minio.entrypoints=web'
      - 'traefik.http.routers.minio.middlewares=redirect-to-https'
      - 'traefik.http.routers.minio.service=minio'
      # HTTPS Router - API (9000)
      - 'traefik.http.routers.minio-secure.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.minio-secure.entrypoints=websecure'
      - 'traefik.http.routers.minio-secure.tls=true'
      - 'traefik.http.routers.minio-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.minio-secure.service=minio'
      # HTTP Router - Console (9001)
      - 'traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.minio-console.entrypoints=web'
      - 'traefik.http.routers.minio-console.middlewares=redirect-to-https'
      - 'traefik.http.routers.minio-console.service=minio-console'
      # HTTPS Router - Console (9001)
      - 'traefik.http.routers.minio-console-secure.rule=Host(`${MINIO_CONSOLE_DOMAIN_PREFIX}.${DOMAIN}`)'
      - 'traefik.http.routers.minio-console-secure.entrypoints=websecure'
      - 'traefik.http.routers.minio-console-secure.tls=true'
      - 'traefik.http.routers.minio-console-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.minio-console-secure.service=minio-console'
      # Services
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'
      - 'traefik.http.services.minio-console.loadbalancer.server.port=9001'
      # Middleware for HTTPS redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - shared_network

  minio-init:
    image: ${DOCKER_CLIENT_IMAGE}:${DOCKER_CLIENT_TAG}
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 20;
      echo 'MinIO is up!';
      echo 'Setting up MinIO...';
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p myminio/${MINIO_DEFAULT_BUCKETS} &&
      echo 'Applying CORS configuration...';
      mc cors set myminio/${MINIO_DEFAULT_BUCKETS} /cors.xml;
      echo 'CORS configuration applied successfully!';
      "
    volumes:
      - ./config/minio-cors.xml:/cors.xml:ro
    networks:
      - shared_network

networks:
  shared_network:
    external: true