services:
  agent-zero:
    image: agent0ai/agent-zero:${DOCKER_TAG:-latest}
    container_name: agent-zero
    restart: unless-stopped
    volumes:
      - ./data/memory:/memory
      - ./data/knowledge:/knowledge
      - ./data/instruments:/instruments
      - ./data/tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ:-UTC}
      # LLM API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - LM_STUDIO_BASE_URL=${LM_STUDIO_BASE_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SAMBANOVA_API_KEY=${SAMBANOVA_API_KEY}
      - VENICE_API_KEY=${VENICE_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - OPENAI_COMPATIBLE_BASE_URL=${OPENAI_COMPATIBLE_BASE_URL}
      - OPENAI_COMPATIBLE_API_KEY=${OPENAI_COMPATIBLE_API_KEY}
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent-zero.rule=Host(`${DOMAIN_PREFIX:-agent-zero}.${DOMAIN}`)"
      - "traefik.http.routers.agent-zero.entrypoints=websecure"
      - "traefik.http.routers.agent-zero.tls.certresolver=cloudflare"
      - "traefik.http.services.agent-zero.loadbalancer.server.port=80"

networks:
  shared_network:
    external: true