services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "96m"
        max-file: "5"
    volumes:
      # - ./conf/mongo/:/docker-entrypoint-initdb.d/
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongodb.rule=Host(`${DOMAIN_PREFIX}.${DOMAIN}`)"
      - "traefik.http.routers.mongodb.tls=true"
      - "traefik.http.routers.mongodb.tls.certresolver=cloudflare"
      - "traefik.http.services.mongodb.loadbalancer.server.port=27017"
      - "traefik.tcp.routers.mongodb-tcp.rule=HostSNI(`${DOMAIN_PREFIX}.${DOMAIN}`)"
      - "traefik.tcp.routers.mongodb-tcp.tls=true"
      - "traefik.tcp.routers.mongodb-tcp.tls.certresolver=cloudflare"
      - "traefik.tcp.services.mongodb-tcp.loadbalancer.server.port=27017"

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  shared_network:
    external: true